## Extração de dados da Steam

### Anos de 2023 e 2024

Importação do request para fazer os pedidos ao site

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import sys
import os

### Teste

In [2]:
link_mensal_2023 = ['https://web.archive.org/web/20230223130822/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20230324031020/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20230427200029/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20230520184615/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20230621110526/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20230726080827/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20230827005012/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20230925072910/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20231025033018/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20231123010539/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20231223154008/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20240118111931/https://store.steampowered.com/hwsurvey']

In [3]:
meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

In [4]:
import time
def csv_creator(links_meses, ano, meses):
    i = 0
    ids_categorias = [('osversion_details', 'OS Version'), ('cat0_details', 'System RAM'), ('cat2_details', 'Physical CPUs'), ('cat3_details', 'Video Card Description'), ('cat4_details', 'VRAM'), ('cat5_details', 'Primary Display Resolution')]

    with open(f'dados_mensais_{ano}.csv', 'w', encoding='utf-8') as f:
        f.write('Categoria,Especificação,Porcentagens,Incrementos/Decrementos,Mês,Ano\n')
    
    for link in links_meses:
        time.sleep(5)
        html = requests.get(link).text
        soup = BeautifulSoup(html, 'html.parser')

        for id_, categoria in ids_categorias:
            div = soup.find('div', id=f'{id_}')
            titulos = div.find_all('div', class_='stats_col_mid')
            porcentagens = div.find_all('div', class_='stats_col_right')
            incs_decs = div.find_all('div', class_='stats_col_right2')

            with open(f'dados_mensais_{ano}.csv', 'a+', encoding='utf-8') as f:
                for titulo, porcentagem, inc_dec in zip(titulos, porcentagens, incs_decs):
                    #Os espaços daqui também
                    f.write(f"{categoria},{titulo.text.strip()},{porcentagem.text.strip()},{inc_dec.text.strip()},{meses[i]},{ano}\n")
            
        i += 1

In [5]:
link_mensal_2024 = ['https://web.archive.org/web/20240222222446/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20240321031400/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20240418143723/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20240523175529/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20240621130112/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20240727073021/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20240823185528/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20240925062001/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20241023163048/https://store.steampowered.com/hwsurvey',
                    'https://web.archive.org/web/20241123003845/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20241226190453/https://store.steampowered.com/hwsurvey/',
                    'https://web.archive.org/web/20250123170629/https://store.steampowered.com/hwsurvey/']

In [ ]:
csv_creator(link_mensal_2023, 2023, meses)

In [ ]:
csv_creator(link_mensal_2024, 2024, meses)

In [ ]:
df_2023 = pd.read_csv("dados_mensais_2023.csv")

## Visualização dos dados

In [ ]:
df_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 2322 entries, 0 to 2321
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Categoria                 2322 non-null   str
 1    Especificação            2322 non-null   str
 2    Porcentagens             2322 non-null   str
 3    Incrementos/Decrementos  2322 non-null   str
 4    Mês                      2322 non-null   str
 5    Ano                      2322 non-null   int64
dtypes: int64(1), str(5)
memory usage: 109.0 KB

In [ ]:
print(f"--- Dados de 2023 ---")
print(f"  Linhas: {len(df_2023)}")
print(f"  Meses: {df_2023[' Mês'].unique().tolist()}")
print(f"  Anos: {df_2023[' Ano'].unique().tolist()}")
print(f"  Categorias: {df_2023['Categoria'].unique().tolist()}")
print()

--- Dados de 2023 ---
  Linhas: 2322
  Meses: [' Janeiro', ' Fevereiro', ' Março', ' Abril', ' Maio', ' Junho', ' Julho', ' Agosto', ' Setembro', ' Outubro', ' Novembro', ' Dezembro']
  Anos: [2023]
  Categorias: ['OS Version', 'System RAM', 'Physical CPUs', 'Video Card Description', 'VRAM', 'Primary Display Resolution']

# Criação dos dados anuais de 2023

## Limpeza e conversão de tipos

### Remover espaço vazio a esquerda das colunas

In [ ]:
df_2023.columns = df_2023.columns.str.lstrip()

In [ ]:
df_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 2322 entries, 0 to 2321
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Categoria                2322 non-null   str
 1   Especificação            2322 non-null   str
 2   Porcentagens             2322 non-null   str
 3   Incrementos/Decrementos  2322 non-null   str
 4   Mês                      2322 non-null   str
 5   Ano                      2322 non-null   int64
dtypes: int64(1), str(5)
memory usage: 109.0 KB

### Remoção dos espaços a esquerda dos valores da coluna mês

In [ ]:
df_2023['Mês'] = df_2023['Mês'].astype(str).str.lstrip()

In [ ]:
print(f"  Meses: {df_2023['Mês'].unique().tolist()}")

  Meses: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

### Conversão de incremento e porcentagem para float

In [ ]:
df_2023['Porcentagens'] = (df_2023['Porcentagens'].str.replace('%', '', regex=False).str.strip().astype(float))
df_2023['Incrementos/Decrementos'] = (df_2023['Incrementos/Decrementos'].str.replace('%', '', regex=False).str.strip().astype(float))

In [ ]:
print(df_2023.dtypes)
df_2023.head()

Categoria                      str
Especificação                  str
Porcentagens               float64
Incrementos/Decrementos    float64
Mês                            str
Ano                          int64
dtype: object

,Categoria,Especificação,Porcentagens,Incrementos/Decrementos,Mês,Ano
0,OS Version,Windows,96.02,-0.13,Janeiro,2023
1,OS Version,Windows 10 64 bit,63.46,-1.96,Janeiro,2023
2,OS Version,Windows 11 64 bit,30.33,1.91,Janeiro,2023
3,OS Version,Windows 7 64 bit,1.60,-0.06,Janeiro,2023
4,OS Version,Windows 8.1 64 bit,0.39,-0.02,Janeiro,2023

## Criação dos valores anuais.

Para criar os valores anuais pegaremos os valores de Dezembro como referência e subtrairemos pelos valores da primeira aparição daquela especificação ao longo dos meses daquele ano evitando o erro de peças que estão em dezembro mas não aparecem necessariamente em janeiro.

- Utilização dos valores de dezembro

In [ ]:
dezembro = (
    df_2023[df_2023['Mês'] == 'Dezembro']
    [['Ano', 'Categoria', 'Especificação', 'Porcentagens']]
    .copy()
)

In [ ]:
print(f"Registros em Dezembro: {len(dezembro)}")
dezembro.head()

Registros em Dezembro: 199

       Ano   Categoria        Especificação  Porcentagens
2123  2023  OS Version              Windows         96.40
2124  2023  OS Version    Windows 10 64 bit         53.45
2125  2023  OS Version    Windows 11 64 bit         41.95
2126  2023  OS Version     Windows 7 64 bit          0.68
2127  2023  OS Version   Windows 8.1 64 bit          0.15

- Primeira aparição

O groupby faz agrupa os dados e pega a primeira linha de cada grupo

In [ ]:
primeira = (df_2023.groupby(['Ano', 'Categoria', 'Especificação'], as_index=False).first()
    [['Ano', 'Categoria', 'Especificação', 'Porcentagens', 'Mês']]
    .rename(columns={'Porcentagens': 'Porcentagem_Inicial','Mês': 'Primeiro_Mês'})
)

- União dos meses

O merge faz a união dos dois dataset a partir das chaves ano, categoria e especificação

In [ ]:
resultado = pd.merge(dezembro,primeira,on=['Ano', 'Categoria', 'Especificação'],how='inner')

resultado['Incrementos/Decrementos'] = (resultado['Porcentagens'] - resultado['Porcentagem_Inicial']).round(2)

- Criação do csv

A variável CSV final serve pra ignorar algumas colunas que foram criadas e deixar no formado dos dados mensais mas sem a coluna mês

In [ ]:
csv_final = resultado[[
    'Categoria', 'Especificação', 'Porcentagens', 'Incrementos/Decrementos',
    'Ano'
]]

ARQUIVO_SAIDA = 'dados_anuais_2023.csv'

csv_final.to_csv(ARQUIVO_SAIDA, index=False)

# Criação dos dados anuais de 2024

### Leitura dos dados de 2024

In [6]:
df_2024 = pd.read_csv("dados_mensais_2024.csv")

In [7]:
df_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 2313 entries, 0 to 2312
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Categoria                 2313 non-null   str
 1    Especificação            2313 non-null   str
 2    Porcentagens             2313 non-null   str
 3    Incrementos/Decrementos  2313 non-null   str
 4    Mês                      2313 non-null   str
 5    Ano                      2313 non-null   int64
dtypes: int64(1), str(5)
memory usage: 108.6 KB

### Remoção dos espaços vazios a esquerda das colunas

In [8]:
df_2024.columns = df_2024.columns.str.lstrip()

In [9]:
df_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 2313 entries, 0 to 2312
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Categoria                2313 non-null   str
 1   Especificação            2313 non-null   str
 2   Porcentagens             2313 non-null   str
 3   Incrementos/Decrementos  2313 non-null   str
 4   Mês                      2313 non-null   str
 5   Ano                      2313 non-null   int64
dtypes: int64(1), str(5)
memory usage: 108.6 KB

### Remoção do espaço a esquerda dos meses na coluna mês

In [10]:
df_2024['Mês'] = df_2024['Mês'].astype(str).str.lstrip()

In [11]:
print(f"  Meses: {df_2024['Mês'].unique().tolist()}")

  Meses: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

### Conversões para float

In [12]:
df_2024['Porcentagens'] = (df_2024['Porcentagens'].str.replace('%', '', regex=False).str.strip().astype(float))
df_2024['Incrementos/Decrementos'] = (df_2024['Incrementos/Decrementos'].str.replace('%', '', regex=False).str.strip().astype(float))

In [13]:
df_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 2313 entries, 0 to 2312
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Categoria                2313 non-null   str
 1   Especificação            2313 non-null   str
 2   Porcentagens             2313 non-null   float64
 3   Incrementos/Decrementos  2313 non-null   float64
 4   Mês                      2313 non-null   str
 5   Ano                      2313 non-null   int64
dtypes: float64(2), int64(1), str(3)
memory usage: 108.6 KB

### Primeira aparição

In [15]:
primeira_2024 = (df_2024.groupby(['Ano', 'Categoria', 'Especificação'], as_index=False).first()
    [['Ano', 'Categoria', 'Especificação', 'Porcentagens', 'Mês']]
    .rename(columns={'Porcentagens': 'Porcentagem_Inicial','Mês': 'Primeiro_Mês'})
)

### Data de dezembro de 2024

In [14]:
dezembro_2024 = (
    df_2024[df_2024['Mês'] == 'Dezembro']
    [['Ano', 'Categoria', 'Especificação', 'Porcentagens']]
    .copy()
)

### União dos datasets com a subtração de dezembro - primeira aparição

In [16]:
resultado_2024 = pd.merge(dezembro_2024,primeira_2024,on=['Ano', 'Categoria', 'Especificação'],how='inner')

resultado_2024['Incrementos/Decrementos'] = (resultado_2024['Porcentagens'] - resultado_2024['Porcentagem_Inicial']).round(2)

### Criação do csv

In [18]:
csv_final_2024 = resultado_2024[[
    'Categoria', 'Especificação', 'Porcentagens', 'Incrementos/Decrementos',
    'Ano'
]]

ARQUIVO_SAIDA_2024 = 'dados_anuais_2024.csv'

csv_final_2024.to_csv(ARQUIVO_SAIDA_2024, index=False)