* <h3>FUNÇÃO CSV_CREATOR:</h3>

Essa função, como o nome já diz, cria um csv. Ela pega cada uma das linhas dos dados de hardware da steam, através do método scraping. Através dos ids, ele sempre pega as mesmas linhas em cada um dos meses e escreve linha por linha no arquivo que ele próprio cria, se não existir esse arquivo no computador. Ela recebe uma lista de tuplas com o link referente ao mês, exemplo: [("link", "Janeiro"), ("link", "Fevereiro"), ...]. Com essa lista, ela percorre cada um dos links para pegar todos os meses do ano de uma só vez.

In [1]:
import time
import requests
from bs4 import BeautifulSoup

In [3]:
def csv_creator(links_meses, ano):
    ids_categorias = [('osversion_details', 'OS Version'), ('cat0_details', 'System RAM'), ('cat2_details', 'Physical CPUs'), ('cat3_details', 'Video Card Description'), ('cat4_details', 'VRAM'), ('cat5_details', 'Primary Display Resolution')]

    with open(f'dados_mensais_{ano}.csv', 'w', encoding='utf-8') as f:
                f.write('Categoria, Especificação, Porcentagens, Incrementos/Decrementos, Mês, Ano\n')

    for link, mes in links_meses:
        time.sleep(5)
        html = requests.get(link).text
        soup = BeautifulSoup(html, 'html.parser')

        for id_, categoria in ids_categorias:
            # Pega apenas a div do id especificado (Os ids tem que ser os details para funcionar)
            div = soup.find('div', id=f'{id_}')

            titulos = div.find_all('div', class_='stats_col_mid')
            porcentagens = div.find_all('div', class_='stats_col_right')
            incs_decs = div.find_all('div', class_='stats_col_right2')

            with open(f'dados_mensais_{ano}.csv', 'a+', encoding='utf-8') as f:
                for titulo, porcentagem, inc_dec in zip(titulos, porcentagens, incs_decs):
                    f.write(f"{categoria}, {titulo.text.strip()}, {porcentagem.text.strip()}, {inc_dec.text.strip()}, {mes}, {ano}\n")

#### Arquivo usado para chamar a função referente ao ano de 2019:

In [ ]:
links_mes_2019 = [('https://web.archive.org/web/20190203085600/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Janeiro'), 
           ('https://web.archive.org/web/20190322155105/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Fevereiro'), 
           ('https://web.archive.org/web/20190417153349/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Março'), 
           ('https://web.archive.org/web/20190513072058/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Abril'), 
           ('https://web.archive.org/web/20190616163322/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Maio'), 
           ('https://web.archive.org/web/20190703191628/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Junho'), 
           ('https://web.archive.org/web/20190830001952/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Julho'), 
           ('https://web.archive.org/web/20190906194713/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Agosto'), 
           ('https://web.archive.org/web/20191010085406/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Setembro'), 
           ('https://web.archive.org/web/20191102081710/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Outubro'), 
           ('https://web.archive.org/web/20191209230538/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Novembro'), 
           ('https://web.archive.org/web/20200121101548/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Dezembro')]

csv_creator(links_mes_2019, 2019)

#### Arquivo usado para chamar a função referente ao ano de 2020:

O de 2020 está faltando o mês de junho, pois no site utilizado não tinha como pegar o link de junho

In [ ]:
links_mes_2020 = [('https://web.archive.org/web/20200202095248/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Janeiro'), 
           ('https://web.archive.org/web/20200316152704/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Fevereiro'), 
           ('https://web.archive.org/web/20200407072208/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Março'), 
           ('https://web.archive.org/web/20200505150638/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Abril'), 
           ('https://web.archive.org/web/20200608014405/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Maio'), 
           ('https://web.archive.org/web/20200808140607/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Julho'), 
           ('https://web.archive.org/web/20200908144606/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Agosto'), 
           ('https://web.archive.org/web/20201009143637/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Setembro'), 
           ('https://web.archive.org/web/20201104192639/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Outubro'), 
           ('https://web.archive.org/web/20201209234627/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Novembro'), 
           ('https://web.archive.org/web/20210105073410/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam', 'Dezembro')]

csv_creator(links_mes_2020, 2020)

## Busca dos dados de Junho de 2020

##### Os dados desse mês não estão no site utilizado, então usaremos um CSV já "pronto". Entretanto, os dados desse CSV não estão no mesmo formato do CSV criado pelo csv_creator. Então precisamos padronizá-lo para encaixar junto ao nosso

* Importação da bibilioteca Pandas

In [16]:
import pandas as pd

* Leitura do CSV pronto da internet

In [17]:
df = pd.read_csv('junho_2020.csv')
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        193 non-null    str
 1   category    193 non-null    str
 2   name        192 non-null    str
 3   change      193 non-null    float64
 4   percentage  193 non-null    float64
dtypes: float64(2), str(3)
memory usage: 7.7 KB

         date    category                           name  change  percentage
0  2020-06-01  OS Version            "Arch Linux" 64 bit  0.0000      0.0010
1  2020-06-01  OS Version         "Manjaro Linux" 64 bit  0.0000      0.0010
2  2020-06-01  OS Version  Linux Mint 19.3 Tricia 64 bit  0.0000      0.0007
3  2020-06-01  OS Version           MacOS 10.11.6 64 bit -0.0002      0.0012
4  2020-06-01  OS Version           MacOS 10.12.6 64 bit -0.0003      0.0016

* Deletando a coluna "date", já que não usamos nesse formato de data

In [18]:
df.drop('date', axis=1, inplace=True)
df

,category,name,change,percentage
0,OS Version,"""Arch Linux"" 64 bit",0.0000,0.0010
1,OS Version,"""Manjaro Linux"" 64 bit",0.0000,0.0010
2,OS Version,Linux Mint 19.3 Tricia 64 bit,0.0000,0.0007
3,OS Version,MacOS 10.11.6 64 bit,-0.0002,0.0012
4,OS Version,MacOS 10.12.6 64 bit,-0.0003,0.0016
...,...,...,...,...
188,Primary Display Resolution,2560 x 1080,0.0000,0.0113
189,Primary Display Resolution,2560 x 1440,0.0017,0.0623
190,Primary Display Resolution,3440 x 1440,0.0005,0.0087
191,Primary Display Resolution,3840 x 2160,-0.0005,0.0212
192,Primary Display Resolution,Other,-0.0007,0.0200

* Renomeando as colunas para ficar igual ao padrão do csv_creator

In [19]:
colunas = {'category': 'Categoria', 'name': 'Especificação', 'change': 'Incrementos/Decrementos', 'percentage': 'Porcentagens'}

df = df.rename(columns=colunas)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Categoria                193 non-null    str
 1   Especificação            192 non-null    str
 2   Incrementos/Decrementos  193 non-null    float64
 3   Porcentagens             193 non-null    float64
dtypes: float64(2), str(2)
memory usage: 6.2 KB

,Categoria,Especificação,Incrementos/Decrementos,Porcentagens
0,OS Version,"""Arch Linux"" 64 bit",0.0000,0.0010
1,OS Version,"""Manjaro Linux"" 64 bit",0.0000,0.0010
2,OS Version,Linux Mint 19.3 Tricia 64 bit,0.0000,0.0007
3,OS Version,MacOS 10.11.6 64 bit,-0.0002,0.0012
4,OS Version,MacOS 10.12.6 64 bit,-0.0003,0.0016

* As porcentagens desse CSV estão no valor literal delas e não em formato de porcentagem. Por isso, precisamos multiplicar o valor por 100 em cada linha e arredondar para 2 casas decimais para ficar igual ao padrão do csv_creator

In [20]:
colunas_porcentagem = ['Incrementos/Decrementos', 'Porcentagens']
df[colunas_porcentagem] = (df[colunas_porcentagem] * 100).round(2)
df.head()

,Categoria,Especificação,Incrementos/Decrementos,Porcentagens
0,OS Version,"""Arch Linux"" 64 bit",0.00,0.10
1,OS Version,"""Manjaro Linux"" 64 bit",0.00,0.10
2,OS Version,Linux Mint 19.3 Tricia 64 bit,0.00,0.07
3,OS Version,MacOS 10.11.6 64 bit,-0.02,0.12
4,OS Version,MacOS 10.12.6 64 bit,-0.03,0.16

* Alterando a ordem das colunas para ficar no mesmo padrão

In [21]:
ordem_colunas = ['Categoria', 'Especificação', 'Porcentagens', 'Incrementos/Decrementos']
df = df[ordem_colunas]
df.head()

,Categoria,Especificação,Porcentagens,Incrementos/Decrementos
0,OS Version,"""Arch Linux"" 64 bit",0.10,0.00
1,OS Version,"""Manjaro Linux"" 64 bit",0.10,0.00
2,OS Version,Linux Mint 19.3 Tricia 64 bit,0.07,0.00
3,OS Version,MacOS 10.11.6 64 bit,0.12,-0.02
4,OS Version,MacOS 10.12.6 64 bit,0.16,-0.03

* Adicionando as colunas restantes que faltam referentes ao mês e ano

In [ ]:
df['Mês'] = 'Junho'
df['Ano'] = 2020
df.head()

,Categoria,Especificação,Porcentagens,Incrementos/Decrementos,Mês,Ano
0,OS Version,"""Arch Linux"" 64 bit",0.10,0.00,Junho,2020
1,OS Version,"""Manjaro Linux"" 64 bit",0.10,0.00,Junho,2020
2,OS Version,Linux Mint 19.3 Tricia 64 bit,0.07,0.00,Junho,2020
3,OS Version,MacOS 10.11.6 64 bit,0.12,-0.02,Junho,2020
4,OS Version,MacOS 10.12.6 64 bit,0.16,-0.03,Junho,2020

* Voltando para o formato de CSV

In [26]:
ARQUIVO_SAIDA = 'junho_corrijido_2020.csv'

df.to_csv(ARQUIVO_SAIDA, index=False)

Depois de transformar num CSV, apenas copiei e colei no arquivo: "dados_mensais_2020.csv"

#### Arquivo usado para chamar a função referente ao ano de 2021:

In [ ]:
links_2021 = [
    ("https://web.archive.org/web/20210211165325/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Janeiro"),
    ("https://web.archive.org/web/20210310013538/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Fevereiro"),
    ("https://web.archive.org/web/20210406145322/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Março"),
    ("https://web.archive.org/web/20210507144019/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Abril"),
    ("https://web.archive.org/web/20210612115956/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Maio"),
    ("https://web.archive.org/web/20210711092307/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Junho"),
    ("https://web.archive.org/web/20210810140809/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Julho"),
    ("https://web.archive.org/web/20210913120919/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Agosto"),
    ("https://web.archive.org/web/20211019145205/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Setembro"),
    ("https://web.archive.org/web/20211103003851/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Outubro"),
    ("https://web.archive.org/web/20211215004809/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Novembro"),
    ("https://web.archive.org/web/20220105105617/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam", "Dezembro")
]

csv_creator(links_2021, 2021)

#### Arquivo usado para chamar a função referente ao ano de 2022:

In [5]:
links_mes_2022 = [
    ("https://web.archive.org/web/20220216223201/https://store.steampowered.com/hwsurvey/", "Janeiro"),
    ("https://web.archive.org/web/20220308233319/https://store.steampowered.com/hwsurvey/", "Fevereiro"),
    ("https://web.archive.org/web/20220402235914/https://store.steampowered.com/hwsurvey/", "Março"),
    ("https://web.archive.org/web/20220503173516/https://store.steampowered.com/hwsurvey/", "Abril"),
    ("https://web.archive.org/web/20220603173703/https://store.steampowered.com/hwsurvey/", "Maio"),
    ("https://web.archive.org/web/20220703080035/https://store.steampowered.com/hwsurvey/", "Junho"),
    ("https://web.archive.org/web/20220803214815/https://store.steampowered.com/hwsurvey/", "Julho"),
    ("https://web.archive.org/web/20220903174209/https://store.steampowered.com/hwsurvey/", "Agosto"),
    ("https://web.archive.org/web/20221006180352/https://store.steampowered.com/hwsurvey/", "Setembro"),
    ("https://web.archive.org/web/20221104235848/https://store.steampowered.com/hwsurvey/", "Outubro"),
    ("https://web.archive.org/web/20221203055418/https://store.steampowered.com/hwsurvey/", "Novembro"),
    ("https://web.archive.org/web/20230104022312/https://store.steampowered.com/hwsurvey/", "Dezembro")
]

csv_creator(links_mes_2022, 2022)

#### Arquivo usado para chamar a função referente ao ano de 2023:

In [ ]:
links_mes_2023 = [
    ('https://web.archive.org/web/20230223130822/https://store.steampowered.com/hwsurvey', 'Janeiro'),
    ('https://web.archive.org/web/20230324031020/https://store.steampowered.com/hwsurvey', 'Fevereiro'),
    ('https://web.archive.org/web/20230427200029/https://store.steampowered.com/hwsurvey/', 'Março'),
    ('https://web.archive.org/web/20230520184615/https://store.steampowered.com/hwsurvey', 'Abril'),
    ('https://web.archive.org/web/20230621110526/https://store.steampowered.com/hwsurvey', 'Maio'),
    ('https://web.archive.org/web/20230726080827/https://store.steampowered.com/hwsurvey/', 'Junho'),
    ('https://web.archive.org/web/20230827005012/https://store.steampowered.com/hwsurvey', 'Julho'),
    ('https://web.archive.org/web/20230925072910/https://store.steampowered.com/hwsurvey/', 'Agosto'),
    ('https://web.archive.org/web/20231025033018/https://store.steampowered.com/hwsurvey/', 'Setembro'),
    ('https://web.archive.org/web/20231123010539/https://store.steampowered.com/hwsurvey/', 'Outubro'),
    ('https://web.archive.org/web/20231223154008/https://store.steampowered.com/hwsurvey', 'Novembro'),
    ('https://web.archive.org/web/20240118111931/https://store.steampowered.com/hwsurvey', 'Dezembro')
]

csv_creator(links_mes_2023, 2023)

#### Arquivo usado para chamar a função referente ao ano de 2024:

In [ ]:
links_mes_2024 = [
    ('https://web.archive.org/web/20240222222446/https://store.steampowered.com/hwsurvey', 'Janeiro'),
    ('https://web.archive.org/web/20240321031400/https://store.steampowered.com/hwsurvey/', 'Fevereiro'),
    ('https://web.archive.org/web/20240418143723/https://store.steampowered.com/hwsurvey', 'Março'),
    ('https://web.archive.org/web/20240523175529/https://store.steampowered.com/hwsurvey/', 'Abril'),
    ('https://web.archive.org/web/20240621130112/https://store.steampowered.com/hwsurvey/', 'Maio'),
    ('https://web.archive.org/web/20240727073021/https://store.steampowered.com/hwsurvey/', 'Junho'),
    ('https://web.archive.org/web/20240823185528/https://store.steampowered.com/hwsurvey/', 'Julho'),
    ('https://web.archive.org/web/20240925062001/https://store.steampowered.com/hwsurvey/', 'Agosto'),
    ('https://web.archive.org/web/20241023163048/https://store.steampowered.com/hwsurvey', 'Setembro'),
    ('https://web.archive.org/web/20241123003845/https://store.steampowered.com/hwsurvey/', 'Outubro'),
    ('https://web.archive.org/web/20241226190453/https://store.steampowered.com/hwsurvey/', 'Novembro'),
    ('https://web.archive.org/web/20250123170629/https://store.steampowered.com/hwsurvey/', 'Dezembro')
]

csv_creator(links_mes_2024, 2024)

#### Arquivo usado para chamar a função referente ao ano de 2025:

In [ ]:
links_mes_2025 = [
    ('https://web.archive.org/web/20250220123300/https://store.steampowered.com/hwsurvey', 'Janeiro'),
    ('https://web.archive.org/web/20250321095337/https://store.steampowered.com/hwsurvey', 'Fevereiro'),
    ('https://web.archive.org/web/20250421105211/https://store.steampowered.com/hwsurvey', 'Março'),
    ('https://web.archive.org/web/20250520054016/https://store.steampowered.com/hwsurvey', 'Abril'),
    ('https://web.archive.org/web/20250620212251/https://store.steampowered.com/hwsurvey', 'Maio'),
    ('https://web.archive.org/web/20250720135921/https://store.steampowered.com/hwsurvey', 'Junho'),
    ('https://web.archive.org/web/20250820191650/https://store.steampowered.com/hwsurvey', 'Julho'),
    ('https://web.archive.org/web/20250920044413/https://store.steampowered.com/hwsurvey', 'Agosto'),
    ('https://web.archive.org/web/20251021102446/https://store.steampowered.com/hwsurvey', 'Setembro'),
    ('https://web.archive.org/web/20251121052510/https://store.steampowered.com/hwsurvey', 'Outubro'),
    ('https://web.archive.org/web/20251220102808/https://store.steampowered.com/hwsurvey', 'Novembro'),
    ('https://web.archive.org/web/20260120232030/https://store.steampowered.com/hwsurvey', 'Dezembro')
]

csv_creator(links_mes_2025, 2025)

#### Arquivo usado para chamar a função referente ao ano de 2026:

In [ ]:
links_mes_2026 = [
    ('https://web.archive.org/web/20260220193758/https://store.steampowered.com/hwsurvey', 'Janeiro'),
    ('https://web.archive.org/web/20260319195120/https://store.steampowered.com/hwsurvey', 'Fevereiro'),
    ('https://web.archive.org/web/20260421031448/https://store.steampowered.com/hwsurvey', 'Março'),
    ('https://web.archive.org/web/20260520195334/https://store.steampowered.com/hwsurvey', 'Abril'),
    ('https://web.archive.org/web/20260622184908/https://store.steampowered.com/hwsurvey', 'Maio')
]

csv_creator(links_mes_2026, 2026)